[project]
name = "pdf-accessibility-project"
version = "0.0.0"
description = "Experimentation with veraPDF"
readme = "https://github.com/birkin/pdf_accessibility_project/blob/main/README.md"
requires-python = ">=3.12,<3.13"
dependencies = []

[dependency-groups]
local = []
staging = []
prod = []
